version: "3.7"
services:
  app:
    container_name: docker-debug-test
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/home/node/app"
      - "/home/node/app/node_modules"
    ports:
      - "8080:8080"
